#!/usr/bin/env sh
npm test > /dev/null 2>&1
TEST_EXIT_CODE=$?
if [ $TEST_EXIT_CODE -ne 0 ]; then
  echo "❌ Tests failed. Please fix the failing tests before pushing."
  npm test
  exit $TEST_EXIT_CODE
fi
echo "✅ All tests passed"
exit 0